/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uni.aed.gui;

import uni.aed.queue.ArrayQueueTDA;
import uni.aed.queue.LinkedQueueTDA;
import uni.aed.queue.PriorityQueueTDA;

/**
 *
 * @author jared
 */
public class FrmColas extends javax.swing.JFrame {
    ArrayQueueTDA<?> ArrayQ;
    LinkedQueueTDA<?> LinkedQ;
    PriorityQueueTDA<?> PriorityQ;
    private final String CADENA_VACIA=""; 
    /**
     * Creates new form FrmColas
     */
    public FrmColas() {
        initComponents();
        StringOption.setSelected(true); // Selecciona una opción por defecto
        initializeQueues();
    }
    private void initializeQueues() {
        if(StringOption.isSelected()){
            ArrayQ = new ArrayQueueTDA<String>(10);
            LinkedQ = new LinkedQueueTDA<String>();
            PriorityQ = new PriorityQueueTDA<String>();
        }else if(IntegerOption.isSelected()){
            ArrayQ = new ArrayQueueTDA<Integer>(10);
            LinkedQ = new LinkedQueueTDA<Integer>();
            PriorityQ = new PriorityQueueTDA<Integer>();
        }
        textoLinkedQ.setText(CADENA_VACIA);
        textoArrayQ.setText(CADENA_VACIA);
        textoPriorityQ.setText(CADENA_VACIA);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        StringOption = new javax.swing.JRadioButton();
        IntegerOption = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        itembar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        priority = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        ArrayQButton = new javax.swing.JRadioButton();
        LinkedQButton = new javax.swing.JRadioButton();
        PriorityQButton = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        textoPriorityQ = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textoLinkedQ = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textoArrayQ = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        reset = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        GetButton = new javax.swing.JButton();
        OfferButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        AddButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(152, 152, 152));

        StringOption.setText("String");
        StringOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StringOptionActionPerformed(evt);
            }
        });

        IntegerOption.setText("Integers");
        IntegerOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IntegerOptionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IntegerOption)
                    .addComponent(StringOption, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(StringOption)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(IntegerOption)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jLabel1.setText("Introduce contenido");

        jLabel2.setText("Introduce prioriedad");

        ArrayQButton.setText("Array Queue");
        ArrayQButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArrayQButtonActionPerformed(evt);
            }
        });

        LinkedQButton.setText("Linked Queue");
        LinkedQButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LinkedQButtonActionPerformed(evt);
            }
        });

        PriorityQButton.setText("Priority Queue");
        PriorityQButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PriorityQButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Ubuntu Mono", 1, 13)); // NOI18N
        jLabel3.setText("Selecciona el tipo de cola");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(ArrayQButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LinkedQButton)
                .addGap(93, 93, 93)
                .addComponent(PriorityQButton)
                .addGap(31, 31, 31))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ArrayQButton)
                    .addComponent(LinkedQButton)
                    .addComponent(PriorityQButton))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        textoPriorityQ.setColumns(20);
        textoPriorityQ.setRows(5);
        jScrollPane3.setViewportView(textoPriorityQ);

        jLabel6.setText("Priority Queue");

        textoLinkedQ.setColumns(20);
        textoLinkedQ.setRows(5);
        jScrollPane2.setViewportView(textoLinkedQ);

        jLabel5.setText("Linked Queue");

        textoArrayQ.setColumns(20);
        textoArrayQ.setRows(5);
        jScrollPane1.setViewportView(textoArrayQ);

        jLabel4.setText("ArrayQueue");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        reset.setText("RESET");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        GetButton.setText("Get");
        GetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetButtonActionPerformed(evt);
            }
        });

        OfferButton.setText("Offer");
        OfferButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OfferButtonActionPerformed(evt);
            }
        });

        DeleteButton.setText("Delete");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        AddButton.setText("Add");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AddButton)
                    .addComponent(DeleteButton)
                    .addComponent(OfferButton)
                    .addComponent(GetButton))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(AddButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DeleteButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OfferButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GetButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addComponent(reset)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(itembar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(priority, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(itembar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(priority, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(reset)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PriorityQButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PriorityQButtonActionPerformed
        // TODO add your handling code here:
        LinkedQButton.setSelected(false);
        ArrayQButton.setSelected(false);
    }//GEN-LAST:event_PriorityQButtonActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        // TODO add your handling code here:
       if(StringOption.isSelected()){
            if(LinkedQButton.isSelected()){ 
                ((LinkedQueueTDA<String>)LinkedQ).add(itembar.getText());
                textoLinkedQ.setText(LinkedQ.toString());
            } else if(ArrayQButton.isSelected()){
                // Agregar el elemento a ListQ
                ((ArrayQueueTDA<String>)ArrayQ).add(itembar.getText());
                textoArrayQ.setText(ArrayQ.toString());
            } else if(PriorityQButton.isSelected()){
                // Agregar el elemento a ArrayQ con prioridad si es una cola de prioridad
                ((PriorityQueueTDA<String>)PriorityQ).add(itembar.getText());
                textoPriorityQ.setText(PriorityQ.toString());
            }
        } else if(IntegerOption.isSelected()){
            try {
                Integer number = Integer.parseInt(itembar.getText());
                if(LinkedQButton.isSelected()){
                    ((LinkedQueueTDA<Integer>)LinkedQ).add(number);                
                    textoLinkedQ.setText(LinkedQ.toString());
                } else if(ArrayQButton.isSelected()){
                    // Agregar el elemento a ListQ
                    ((ArrayQueueTDA<Integer>)ArrayQ).add(number);
                    textoArrayQ.setText(ArrayQ.toString());
                } else if(PriorityQButton.isSelected()){
                    // Agregar el elemento a ArrayQ con prioridad si es una cola de prioridad
                    ((PriorityQueueTDA<Integer>)PriorityQ).add(number);
                    textoPriorityQ.setText(PriorityQ.toString());
                }
            } catch (NumberFormatException e) {
                // Manejar el error cuando el texto no sea un número
            }
        }
    }//GEN-LAST:event_AddButtonActionPerformed

    private void OfferButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OfferButtonActionPerformed
        // TODO add your handling code here:
        Integer p = Integer.parseInt(priority.getText());
        if(StringOption.isSelected()){
            ((PriorityQueueTDA<String>)PriorityQ).offer(itembar.getText(),p);
        }else if(IntegerOption.isSelected()){
            Integer number = Integer.parseInt(itembar.getText());
            ((PriorityQueueTDA<Integer>)PriorityQ).offer(number,p);
        }
    }//GEN-LAST:event_OfferButtonActionPerformed

    private void StringOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StringOptionActionPerformed
        // TODO add your handling code here:
        IntegerOption.setSelected(false);
        initializeQueues();
    }//GEN-LAST:event_StringOptionActionPerformed

    private void IntegerOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IntegerOptionActionPerformed
        // TODO add your handling code here:
        StringOption.setSelected(false);
        initializeQueues();
    }//GEN-LAST:event_IntegerOptionActionPerformed

    private void ArrayQButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArrayQButtonActionPerformed
        // TODO add your handling code here:
        LinkedQButton.setSelected(false);
        PriorityQButton.setSelected(false);
    }//GEN-LAST:event_ArrayQButtonActionPerformed

    private void LinkedQButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LinkedQButtonActionPerformed
        // TODO add your handling code here:
        ArrayQButton.setSelected(false);
        PriorityQButton.setSelected(false);
    }//GEN-LAST:event_LinkedQButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        // TODO add your handling code here:
        if(LinkedQButton.isSelected()){ 
                LinkedQ.delete();
                textoLinkedQ.setText(CADENA_VACIA);
            } else if(ArrayQButton.isSelected()){
                // Agregar el elemento a ListQ
                ArrayQ.delete();
                textoArrayQ.setText(CADENA_VACIA);

            } else if(PriorityQButton.isSelected()){
                // Agregar el elemento a ArrayQ con prioridad si es una cola de prioridad
                PriorityQ.delete();
                textoPriorityQ.setText(CADENA_VACIA);
            }
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void GetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetButtonActionPerformed
        // TODO add your handling code here:
        if(LinkedQButton.isSelected()){ 
                textoLinkedQ.setText(LinkedQ.toString());
            } else if(ArrayQButton.isSelected()){
                // Agregar el elemento a ListQ
                textoArrayQ.setText(ArrayQ.toString());
            } else if(PriorityQButton.isSelected()){
                // Agregar el elemento a ArrayQ con prioridad si es una cola de prioridad
                textoPriorityQ.setText(PriorityQ.toString());
            }
    }//GEN-LAST:event_GetButtonActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        initializeQueues();
    }//GEN-LAST:event_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmColas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmColas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmColas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmColas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmColas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JRadioButton ArrayQButton;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton GetButton;
    private javax.swing.JRadioButton IntegerOption;
    private javax.swing.JRadioButton LinkedQButton;
    private javax.swing.JButton OfferButton;
    private javax.swing.JRadioButton PriorityQButton;
    private javax.swing.JRadioButton StringOption;
    private javax.swing.JTextField itembar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField priority;
    private javax.swing.JButton reset;
    private javax.swing.JTextArea textoArrayQ;
    private javax.swing.JTextArea textoLinkedQ;
    private javax.swing.JTextArea textoPriorityQ;
    // End of variables declaration//GEN-END:variables
}
